apiVersion: v1
kind: Namespace
metadata:
  name: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
  namespace: blue
  labels:
    app: blue-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      volumes:
        - name: blue-pv-storage
          persistentVolumeClaim:
            claimName: blue-pvc
      containers:
        - name: blue-writer
          image: blue-editor:latest
          volumeMounts:
            - name: blue-pv-storage
              mountPath: /app/data
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: BLUE_WRITER
            - name: PORT
              value: "5000"
          readinessProbe:
            httpGet:
              port: 5000
            periodSeconds: 3

          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
        - name: blue-reader
          image: blue-editor:latest
          volumeMounts:
            - name: blue-pv-storage
              mountPath: /app/data
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: BLUE_READER
            - name: PORT
              value: "5001"
          readinessProbe:
            httpGet:
              path: /read
              port: 5001
            periodSeconds: 3
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: blue-app-service
  namespace: blue
spec:
  selector:
    app: blue-app
  ports:
    - protocol: TCP
      name: blue-writer
      port: 5000
    - protocol: TCP
      name: blue-reader
      port: 5001
  # targetPort defaults to port
  # don't need a type here when used with ingress
  # type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blue-pvc
  namespace: blue
  annotations:
    volumeType: local
spec:
  # Uses local-path-provisioner, but in KIND for Kubernetes in Docker, it is provisioned as standard
  # storageClassName: local-path
  # In Kind, doesn't support ReadWriteOncePod, so use RadWriteOnce
  accessModes:
    # - ReadWriteOncePod
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: blue
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /read
        backend:
          service:
            name: blue-app-service
            port:
               name: blue-reader
      - pathType: Prefix
        path: /write
        backend:
          service:
            name: blue-app-service
            port:
              name: blue-writer
---