apiVersion: v1
kind: Namespace
metadata:
  name: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
  namespace: blue
  labels:
    app: blue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: blue-writer
          image: aramadia/blue-writer:latest
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
        - name: blue-reader
          image: aramadia/blue-reader:latest
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
