apiVersion: v1
kind: Namespace
metadata:
  name: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
  namespace: blue
  labels:
    app: blue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      volumes:
        - name: blue-pv-storage
          persistentVolumeClaim:
            claimName: blue-pvc
      containers:
        - name: blue-writer
          image: blue-writer:latest
          volumeMounts:
            - name: blue-pv-storage
              mountPath: /app/data
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
        - name: blue-reader
          image: blue-reader:latest
          volumeMounts:
            - name: blue-pv-storage
              mountPath: /app/data
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: blue-app-service
  namespace: blue
spec:
  selector:
    app: blue-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blue-pvc
  namespace: blue
  annotations:
    volumeType: local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi
