apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
metadata:
  name: eks-workshop
  region: us-west-2
  version: "1.30"
  tags:
    karpenter.sh/discovery: eks-workshop
    created-by: eks-workshop-v2
    env: eks-workshop
iam:
  withOIDC: true
vpc:
  cidr: 10.42.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
addons:
  - name: vpc-cni
    version: 1.16.0
    configurationValues: '{"env":{"ENABLE_PREFIX_DELEGATION":"true", "ENABLE_POD_ENI":"true", "POD_SECURITY_GROUP_ENFORCING_MODE":"standard"},"enableNetworkPolicy": "true", "nodeAgent": {"enablePolicyEventLogs": "true"}}'
    resolveConflicts: overwrite
managedNodeGroups:
  - name: default
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    instanceType: m5a.large
    privateNetworking: true
    releaseVersion: "1.30.0-20240625"
    updateConfig:
      maxUnavailablePercentage: 50
    labels:
      workshop-default: "yes"
