name: Create Cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          echo ${{ github.workspace }}
          echo $GITHUB_PATH GITHUB_PATH
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1