name: Create Cluster

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          echo ${{ github.workspace }}
          echo $GITHUB_PATH GITHUB_PATH
          # This is necessary to make the docker socket available from the container since its currently owned by root
          sudo chmod 777 /var/run/docker.sock

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: action-blue-cluster # Kind adds the prefix kind- to the cluster name
          config: kind-cluster.yaml
      - name: Use cluster
        run: |
          kubectl cluster-info --context kind-action-blue-cluster
          kubectl get pods
          ./test.sh

          